version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.18
  aws-s3: circleci/aws-s3@1.0.11


jobs:
  build:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/wordtoken/www
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dep-{{ .Branch }}-{{ .Revision }}
            - dep-{{ .Branch }}-
            - dep-
      - run:
          name: install node dependencies 
          command: npm install
      - save_cache:
          paths:
            - .git
            - node_modules
            - src
          key: dep-{{ .Branch }}-{{ .Revision }}
      - run:
          name: build gatsby files
          command: npx gatsby build
      - persist_to_workspace:
          root: ~/wordtoken/www
          paths:
            - public
  deploy_qa:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/wordtoken/www
    parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: ~/wordtoken/www
      - aws-s3/sync:
          from: public
          to: "s3://qa.wordtoken.com"
          aws-access-key-id: AWS_ACCESS_KEY_ID_FSN
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_FSN
          aws-region: AWS_REGION_FSN
          arguments: |
            --delete \
            --acl public-read \
            --metadata-directive REPLACE \
            --cache-control "public, max-age=31536000, immutable" \
            --exclude sw.js \
            --exclude page-data/*.json \
            --exclude *.html
      - aws-s3/copy:
          from: public/sw.js
          to: "s3://qa.wordtoken.com"
          aws-access-key-id: AWS_ACCESS_KEY_ID_FSN
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_FSN
          aws-region: AWS_REGION_FSN
          arguments: |
            --acl public-read \
            --metadata-directive REPLACE \
            --cache-control "public, max-age=0, must-revalidate"
      - aws-s3/copy:
          from: public/page-data/
          to: "s3://qa.wordtoken.com"
          aws-access-key-id: AWS_ACCESS_KEY_ID_FSN
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_FSN
          aws-region: AWS_REGION_FSN
          arguments: |
            --acl public-read \
            --metadata-directive REPLACE \
            --cache-control "public, max-age=0, must-revalidate" \
            --recursive \
            --exclude "*" \
            --include "*.json"
      - aws-s3/copy:
          from: public
          to: "s3://qa.wordtoken.com"
          aws-access-key-id: AWS_ACCESS_KEY_ID_FSN
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_FSN
          aws-region: AWS_REGION_FSN
          arguments: |
            --acl public-read \
            --metadata-directive REPLACE \
            --cache-control "public, max-age=0, must-revalidate" \
            --recursive \
            --exclude "*" \
            --include "*.html"
  deploy_prod:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/wordtoken/www
    parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: ~/wordtoken/www
      - aws-s3/sync:
          from: public
          to: "s3://www.wordtoken.com"
          aws-access-key-id: AWS_ACCESS_KEY_ID_FSN
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_FSN
          aws-region: AWS_REGION_FSN
          arguments: |
            --delete \
            --acl public-read \
            --metadata-directive REPLACE \
            --cache-control "public, max-age=31536000, immutable" \
            --exclude sw.js \
            --exclude page-data/*.json \
            --exclude *.html
      - aws-s3/copy:
          from: public/sw.js
          to: "s3://www.wordtoken.com"
          aws-access-key-id: AWS_ACCESS_KEY_ID_FSN
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_FSN
          aws-region: AWS_REGION_FSN
          arguments: |
            --acl public-read \
            --metadata-directive REPLACE \
            --cache-control "public, max-age=0, must-revalidate"
      - aws-s3/copy:
          from: public/page-data/
          to: "s3://www.wordtoken.com"
          aws-access-key-id: AWS_ACCESS_KEY_ID_FSN
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_FSN
          aws-region: AWS_REGION_FSN
          arguments: |
            --acl public-read \
            --metadata-directive REPLACE \
            --cache-control "public, max-age=0, must-revalidate" \
            --recursive \
            --exclude "*" \
            --include "*.json"
      - aws-s3/copy:
          from: public
          to: "s3://www.wordtoken.com"
          aws-access-key-id: AWS_ACCESS_KEY_ID_FSN
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_FSN
          aws-region: AWS_REGION_FSN
          arguments: |
            --acl public-read \
            --metadata-directive REPLACE \
            --cache-control "public, max-age=0, must-revalidate" \
            --recursive \
            --exclude "*" \
            --include "*.html"
      
workflows:
  build_hold_and_deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy_qa:
          requires:
            - hold
          filters:
           branches:
            only:
              - qa
      - deploy_prod:
          requires:
            - hold
          filters:
           branches:
            only:
              - master